backend:
  name: github
  repo: tecs-usp/Portal_Indigena_2021
  branch: master # Branch to update (optional; defaults to master)
media_folder: "Portal/assets/uploads"
collections:
  - name: aldeias
    label: "Aldeias"
    folder: "Portal/_aldeias/"
    extension: html
    create: true
    editor:
      preview: false
    fields:
      - { label: Layout, name: layout, widget: string, default: aldeia }
      - { label: Titulo, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }
  - name: i18n
    label: "Traducoes"
    folder: "Portal/_i18n/"
    extension: yml
    create: true
    editor:
      preview: false
    fields:
      - { label: Layout, name: layout, widget: string, default: aldeia }
      - { label: Titulo, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }
  - name: "config"
    label: "Config"
    editor:
      preview: false
    files:
      - label: "Navbar"
        name: "navbar"
        file: "Portal/_data/navbar.yml"
        fields:
          - label: "Navbar Mobile Items"
            name: "navbar-mobile"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: string }
              - { label: "Link", name: "link", widget: string }
          - label: "Navbar Items"
            name: "navbar"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: string }
              - { label: "Link", name: "link", widget: string }
              - { label: "SubItems", name: "sub", widget: boolean }
