backend:
  name: github
  repo: tecs-usp/Portal_Indigena_2021
  branch: master # Branch to update (optional; defaults to master)
  site_domain: portalindigena.web.app
site_url: https://portalindigena.web.app
publish_mode: editorial_workflow
media_folder: "Portal/assets/uploads"
logo_url: https://portalindigena.web.app/assets/img/Logo_Vetor2.png
locale: 'pt'
collections:
  - name: idiomas
    label: "Idiomas"
    description: Teste
    files: 
      - label: "Português"
        name: "pt-BR"
        file: "Portal/_i18n/pt.yml"
        fields:
          - {label: Idiomas, name: lingua, widget: text}
          - label: Guaviraty
            name: guaviraty
            widget: list
            fields:
              - {label: Sobre a Aldeia, name: sobre, widget: text}
              - {label: Historia da Aldeia, name: historia, widget: text}
